
name: Ruby CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.2', '3.1', '3.0']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install dependencies
        run: |
          sudo apt-get install gcc pkg-config libxml2-dev libxslt-dev zlib1g-dev
          gem install bundler
          bundle install --jobs 4 --retry 3 
      - name: Run tests
        run: bundle exec rake